apiVersion: v1
kind: Service
metadata:
  name: gatehouse-api
  namespace: gatehouse
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gatehouse-api
  ports:
    - name: http
      port: 80
      targetPort: http
